オブジェクト指向版lsコマンドの提出物です。
FUGA0618/ruby-practices pull request #12
Opened 2021-05-23 06:21 UTC by FUGA0618

レビューよろしくお願いいたします🙏

2021-05-26 03:16 UTC, u1tnk requested changes

2021-05-26 03:16 UTC, u1tnk commented on 08.ls_object/lib/option_a.rb
> +class OptionA
OptionAという名前ですが、これはファイルを探索しているクラスなので違和感を感じます。
本プラクティスでは無いですが、`--ignore=PATTERN` が追加されると名前をどうするか困ってしまいますし。
クラス名は何をやるクラスなのか？で考えると分かりやすいですね。

また、 オプションを変数化するときにAだと分かりづらいのでAllとか longnameの方を使うと分かりやすくなりますね。

2021-05-26 03:16 UTC, u1tnk commented on 08.ls_object/lib/option_a.rb
> +  def initialize(boolean, arg)
argは引数という意味で抽象的過ぎて分かりづらいです。
何がargとして渡ってきてるかを考えて名前を付けましょう。

2021-05-26 03:16 UTC, u1tnk commented on 08.ls_object/lib/option_a.rb
> +  def self.setup_files(arg)
このメソッドは初期化時に呼ばれるものなのでクラスメソッドじゃなくて良いのでは無いかと思います。
また、setupは設定された、準備されたという意味でこの場合は相応しく無いと思います。

2021-05-26 03:16 UTC, u1tnk commented on 08.ls_object/lib/option_a.rb
> +        exit
こまかいところですがエラー時に exitを使う場合デフォルトは0が返ってしまい、正常終了となってしまいます。
https://docs.ruby-lang.org/ja/latest/method/Kernel/m/exit.html

exitで 1や-1を返すのも良いですが、abortという専用メソッドもあるのでそちらでも良いと思います。

https://docs.ruby-lang.org/ja/latest/method/Kernel/m/abort.html

2021-05-26 03:16 UTC, u1tnk commented on 08.ls_object/lib/option_a.rb
> +  attr_reader :use_option, :files
クラス外から使われる必要の無いデータに attr_readerを使う必要はありません。
カプセル化の観点からも必要無ければ無い方が良いですね。

2021-05-26 03:16 UTC, u1tnk commented on 08.ls_object/lib/option_a.rb
> +    if arg.nil?
こういう場合は elseが長くなって読みづらいので

```
return Dir.entries('.') unless arg
```

とすると良くて、guard節と呼ばれます。
rubocopに指摘されそうなのでrubocopかけてみましたが、色々ひっかかってたので対応お願いします。

2021-05-26 03:16 UTC, u1tnk commented on 08.ls_object/ls.rb
> +    target_files = OptionA.new(options['a'], arg).reject_hidden_files
一行でシンプルに書けてるのは良いですね 👍 
ただ、OptionAクラスに reject_hidden_files したら target_files が出てくるというのは分かりづらく無いでしょうか？

例えばボウリングを例にすると、以下のようなメソッドだと分かりやすく無いですか？
これを参考に考えてみてください。

```
score = Game.new(shots).calc_score
```

2021-05-29 01:49 UTC, FUGA0618 commented on 08.ls_object/lib/option_a.rb
> +  def self.setup_files(arg)
クラスメソッドではなく、privateインスタンスメソッドに変更しました。
初期化時はインスタンスメソッドが使えないものと勘違いしていました🙇🏻‍♂️

`setup_files`を、`prepare_files`に修正しました。
prepareは用意する／準備するという意味になるので良いかなと思ったのですがいかがでしょうか。

2021-05-29 01:49 UTC, FUGA0618 commented on 08.ls_object/lib/option_a.rb
> +  attr_reader :use_option, :files
どのインスタンス変数も外部からの参照がないものだったので、削除しました。

2021-05-29 02:54 UTC, FUGA0618 commented on 08.ls_object/lib/option_a.rb
> +        exit
`abort`を使う形に修正しました。

終了時のステータスコードがexitだと0になり、abortだと1になって、デフォルトがそれぞれ正常終了と異常終了になることは理解できました。

この意図としては、
- 正常終了の場合は、その後にまた別の`rescue`によってエラーが捕捉された場合、その処理が実行されてしまう。
- 異常終了の場合はそのようなことがないので、ちゃんと異常終了させてプログラムの実行を中断させるべき。

という認識で合っていますか？

2021-05-29 04:00 UTC, FUGA0618 commented on 08.ls_object/lib/option_a.rb
> +    if arg.nil?
ガード節を使う形に修正しました😊
改めてrubocopをかけてみたのですが、僕の手元ではパスしているようでした。
![スクリーンショット 2021-05-29 13 00 10](https://user-images.githubusercontent.com/58870882/120057423-d9a75800-c07d-11eb-8308-d37a51fa0637.png)

2021-05-29 04:18 UTC, FUGA0618 commented on 08.ls_object/ls.rb
> +    target_files = OptionA.new(options['a'], arg).reject_hidden_files
現状だと何をどうしているのかさっぱりわからないと思いました😅
クラス名を探索を意味する`Search`に、`reject_hidden_files`は`select_files`にして
```ruby
target_files = Search.new(@options['a'], @arg).select_files
```
とすれば挙動が伝わりやすいかと思い修正しましたがいかがでしょうか。

2021-05-29 06:44 UTC, FUGA0618 commented on 08.ls_object/lib/option_a.rb
> +class OptionA
クラス名、変数名等を全体的に見直して修正しました。

2021-05-29 06:44 UTC, FUGA0618 commented on 08.ls_object/lib/option_a.rb
> +  def initialize(boolean, arg)
具体的な引数名に、全体的に修正してみました。

2021-05-29 07:56 UTC, u1tnk commented on 08.ls_object/lib/option_a.rb
> +        exit
いえ、exit の0か1は別のコマンド用ですね。

例えば

```
ls.rb && echo 'success'
```

のよう別のコマンドを繋げるときに 0だと `success` が表示されますが、0以外だと表示されません。
unixコマンドのお作法の話です。

2021-05-29 08:01 UTC, u1tnk commented on 08.ls_object/ls.rb
> +    target_files = OptionA.new(options['a'], arg).reject_hidden_files
はい、だいぶ良くなりましたね！
ただ、クラス名は名詞が一般的です。探索するのなら `Searcher`、ファイルをという目的をつけるなら `FileSearcher`かなー 🤔

2021-05-29 08:49 UTC, u1tnk requested changes

2021-05-29 08:49 UTC, u1tnk commented on 08.ls_object/lib/order.rb
> +  def initialize(boolean, files)
booleanは型の名前なので、何のオプションか分かるようにしましょう。

2021-05-29 08:49 UTC, u1tnk commented on 08.ls_object/lib/order.rb
> +  def sort
Orderとsortは同じような概念の別の単語なので、同じものを指すものに使うと混乱しそうな気がしますね。

2021-05-29 08:49 UTC, u1tnk commented on 08.ls_object/lib/order.rb
> +    @use_option = boolean
まだオプションが各クラス一つの前提のコードになっていますね。
また、オプションの内容が分からないのでオプション内容に即した名前を付けましょう。

2021-05-29 08:49 UTC, u1tnk commented on 08.ls_object/ls.rb
> +    files = Order.new(@reverse, target_files).sort
他に◯◯_filesがある中で filesと来るとどういうファイル配列か分かりづらいので修飾するようにしましょう。

2021-05-29 11:29 UTC, FUGA0618 commented on 08.ls_object/lib/option_a.rb
> +        exit
お作法のお話なのですね🙇🏻‍♂️
実例もありがとうございます！
手元で試してみて、違いがわかりました😊

2021-05-30 10:17 UTC, FUGA0618 commented on 08.ls_object/lib/order.rb
> +    @use_option = boolean
> まだオプションが各クラス一つの前提のコードになっていますね。

という部分なのですが、今回のプラクティスでは「arl」オプションのみに対応すればいいですが、他のオプションにも対応することになった場合を想定して、各クラスでもオプションを複数受け取れるようにしておいた方が良い、という認識で合っていますでしょうか？

2021-05-30 16:06 UTC, u1tnk commented on 08.ls_object/lib/order.rb
> +    @use_option = boolean
回答としてはその通りです。

オブジェクト指向の課題はちゃんと業務に耐えるコードの書き方を身につけてもらうのが目的なのが前提というのが理由です。

とはいえ、探索するクラスに一つしかオプションが無い、今後もその可能性が高いとしてもこの変数名だと可読性が低いので業務のレビューは通さないです。
一つ例として書いてしまうと `use_option`という変数と `target_all_files`という名前を比較するとどちらが読みやすい、意図が分かりやすいでしょうか？

業務においてはソースコードはできる限り読みやすいものを目指すべきと私は思っています。
なるべく色んなところを探さずとも分かるようにする。とはいえ長過ぎると読みづらいのでバランスも大事。
どうしても意図が分からないコードになってしまったらコメントをする…などです。ドキュメントの補完も必要にはなりますが、ソースコードの時点でできる限り意図が伝わるようにするべきです。

もちろんエンジニアの力量やチームの文化によってだいぶ差が出るところではあるので、この課題としてはある程度のレベルでは通しますので、できる限りで良いので考えてみてください。

2021-05-31 12:07 UTC, FUGA0618 commented on 08.ls_object/lib/order.rb
> +  def sort
クラス名を`FileSorter`として、メソッド名を`sort`に変更しました。
`FileSorter.new.sort`という呼び出し方になるのですが、sortが被ってしまうのはよくないでしょうか😅

2021-05-31 12:07 UTC, FUGA0618 commented on 08.ls_object/ls.rb
> +    files = Order.new(@reverse, target_files).sort
`sorted_files`に修正しました！

2021-05-31 12:11 UTC, FUGA0618 commented on 08.ls_object/lib/order.rb
> +    @use_option = boolean
ご丁寧な説明をありがとうございます！
「オプションが増えたとしてもオプションの内容を理解できるような変数名にするべき」という意図だということがわかりました😊

それを踏まえた上で、各変数名、仮引数名を修正してみました。
自分目線では以前より読みやすくなったように感じますが、まだ足りなかったりわかりづらい箇所がありましたらご指摘いただけますと幸いです！

2021-06-01 05:37 UTC, u1tnk commented on 08.ls_object/lib/order.rb
> +  def sort
理想的じゃないけど、十分です！
Sortが主な責務のクラスを作るならこうなると思うので 🙆‍♀️ 

以下は参考。余談というか参考まで。

全然やらなくて良いですが、sort重複を避けるなら `FileSorter#run`とかメソッドを抽象的にするのはアリですね。このパターンだと FileSorterにrun以外のpublic methodが無いレベルで単機能なクラスである必要があります。
検索されたファイルを SearchedFiles…とかの名前でファイル集合のクラスとして実装するなら sortメソッドでも良いでしょうね。

2021-06-01 05:39 UTC, u1tnk commented on 08.ls_object/lib/order.rb
> +    @use_option = boolean
> 「オプションが増えたとしてもオプションの内容を理解できるような変数名にするべき」

書き間違えただけな気がいますが
「オプションが今後増えないとしてもオプションの内容を理解できるような変数名にするべき」
が僕の意図としては正しいです！

2021-06-01 06:13 UTC, u1tnk requested changes

2021-06-01 06:13 UTC, u1tnk commented on 08.ls_object/lib/file_searcher.rb
> +    @target_files = prepare(file_name)
これは無くても良いインスタンス変数ですね。
selectメソッドの中で `@target_files`の変わりに prepareメソッド(initializeで呼ばないならprepareは良くないですね。 target_files という名前のままで良いかなと)を呼べば良さそう。

何度も結果を使いまわすようなパターンでは initializeで呼んで結果を保存する場合もありますが、一般的にクラスを作るだけは軽くて、 searchとか runとかのメソッドを呼ぶと重い処理をするというクラスを使う側のイメージもあり、イメージと差異が少ない方が使いやすいでしょう。

2021-06-01 06:13 UTC, u1tnk commented on 08.ls_object/lib/output_string.rb
> +  def for_use_option
まだ use_optionが残っていますね。
レビュワーによってだったり、分量によって何度も同じ指摘したり、省略したりはしますが、レビュー受ける側としては、指摘された部分と同様の問題が無いか確認するようにしましょう。
僕らもうっかりする事はあるし、新人プログラマあるあるではありますが 😅

2021-06-01 06:13 UTC, u1tnk commented on 08.ls_object/lib/output_string.rb
> +  def determine_path(file_name)
fileからdirectoryか分からないのに引数はfile_nameというのがちょっと分かりづらいですね

またせっかく実装したので消す事は無いですが、 https://docs.ruby-lang.org/ja/latest/method/File/s/dirname.html こちらが使えたのかなと思います。

2021-06-01 10:33 UTC, FUGA0618 commented on 08.ls_object/lib/order.rb
> +  def sort
`run`で抽象的にする方法もあるのですね！

> run以外のpublic methodが無いレベルで単機能なクラスである必要があります。

この点に注意しつつ、今後抽象的にしても良さそうな場合には使ってみたいと思います😊
ありがとうございます！

2021-06-01 10:34 UTC, FUGA0618 commented on 08.ls_object/lib/order.rb
> +    @use_option = boolean
すみません、文脈を読み違えていました🙇🏻‍♂️
訂正ありがとうございます！

2021-06-01 10:55 UTC, FUGA0618 commented on 08.ls_object/lib/file_searcher.rb
> +    @target_files = prepare(file_name)
今回のケースだと、`@target_files`を何度も使い回すような処理はないですし、あえて初期化時に思い処理をさせる必要はないということですね。
初期化時は`@file_name`を生成するようにして、実際の重たい処理は`select`メソッド内でするように修正しました。

2021-06-01 11:00 UTC, FUGA0618 commented on 08.ls_object/lib/output_string.rb
> +  def for_use_option
確認不足でした、すみません🙇🏻‍♂️
同じ指摘をされないようセルフレビューをもう少ししっかりやるようにします。

2021-06-01 11:32 UTC, FUGA0618 commented on 08.ls_object/lib/output_string.rb
> +  def determine_path(file_name)
`file_or_dir`という形に修正しました。

`File.dirname`、完全に見落としていました！ありがとうございます！
せっかく教えていただいたのと、メソッドのロジックとしても使ったほうがシンプルでわかりやすくなると思ったので、`File.dirname`を使用する形に修正しました。

2021-06-01 15:36 UTC, u1tnk approved these changes

2021-06-02 10:23 UTC, merged